site_name: WON Docs
site_url: https://witchcompany.github.io/won-docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: indigo
    - scheme: slate
      primary: cyan
      accent: indigo
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.indexes
    - toc.integrate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - search.highlight
    - search.suggest
  font:
    text: Inter
    code: JetBrains Mono
  icon:
    logo: material/currency-krw
    repo: fontawesome/brands/github

repo_url: https://github.com/witchcompany/won-docs
repo_name: witchcompany/won-docs
edit_uri: ""

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - tables

plugins:
  - search

extra_css:
  - styles/extra.css

nav:
  - Home: docs/index.md
  - Whitepaper: docs/whitepaper.md
  - Getting Started: docs/getting-started.md
  - Concepts:
      - Twin Wallet: docs/concepts/twin-wallet.md
  - Architecture:
      - Overview: docs/architecture/overview.md
  - Flows:
      - Minting: docs/flows/minting.md
  - Operations:
      - Deployment: docs/operations/deployment.md
  - Security: docs/security.md
  - FAQ: docs/faq.md
  - Glossary: docs/glossary.md
